# Homebrew formula for the Anomyze daemon.
#
# Tap:     brew tap Anomyze/anomyze
# Install: brew install anomyze
#
# After install, register the NMH manifest for your Chrome extension:
#   anomyze --install-nmh --extension-id=YOUR_32_CHAR_ID
# Then fully quit and relaunch Chrome.
#
# This formula is regenerated by scripts/ops/release-homebrew.sh — do not
# edit by hand; changes will be overwritten on next release.

class Anomyze < Formula
  desc "Anomyze P2P daemon — encrypted mesh network for Chrome"
  homepage "https://anomyze.com"
  version "0.6.1"
  license "Proprietary"

  on_macos do
    on_arm do
      url "https://download.anomyze.network/releases/daemon/latest/anomyze-darwin-arm64"
      sha256 "4d8c0728b84b0ef8e3467566704927a722e988581ac9e1dd7cd1dd688d3ed2b9"
    end

    on_intel do
      url "https://download.anomyze.network/releases/daemon/latest/anomyze-darwin-amd64"
      sha256 "cb19e063e6da22b35cf82c13ff294209612da3e173562143fef895a54ec0ee9b"
    end
  end

  def install
    if Hardware::CPU.arm?
      bin.install "anomyze-darwin-arm64" => "anomyze"
    else
      bin.install "anomyze-darwin-amd64" => "anomyze"
    end
    # Backwards-compat symlink for users migrating from 'anomyzed' command
    bin.install_symlink "anomyze" => "anomyzed"
  end

  def caveats
    <<~EOS
      After install, register the Chrome Native Messaging Host manifest:
        anomyze --install-nmh --extension-id=YOUR_32_CHAR_ID
      Then FULLY QUIT Chrome (⌘Q on Mac) and relaunch. The extension will
      detect the daemon and connect automatically.

      For the legacy 'anomyzed' command name, a symlink is kept for this
      release line. New scripts should call 'anomyze' directly.
    EOS
  end

  test do
    assert_match "anomyze", shell_output("#{bin}/anomyze --version")
  end
end
